backup:
  downgrade: null
  enabled: true
  install: null
  mode: incremental
  type: rsync
  uninstall: null
  upgrade: null
disk:
  trim:
    after_upgrade: false
download:
  icons: true
  multithreaded: true
  multithreaded_client: null
gems:
- appimage
- arch
- web
- flatpak
locale: null
memory_cache:
  data_expiration: 3600
  icon_expiration: 300
store_root_password: true
suggestions:
  by_type: 10
  enabled: true
system:
  notifications: true
  single_dependency_checking: false
ui:
  auto_scale: false
  hdpi: true
  scale_factor: 1.0
  style: null
  table:
    max_displayed: 50
  tray:
    default_icon: /home/errxr/Downloads/pamac-updater.png
    updates_icon: /home/errxr/Downloads/pamac-updater.png
updates:
  ask_for_reboot: true
  check_interval: 30
